services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - "2314:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./themes/test:/opt/keycloak/themes/test
      